# Generated by Django 4.2.5 on 2023-10-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlink', '0002_linkforit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkForIT',
        ),
    ]
