# Generated by Django 4.2.5 on 2023-11-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlink', '0004_linkforit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLink',
        ),
    ]
