# Generated by Django 4.2.5 on 2023-10-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sid',
            field=models.CharField(max_length=9),
        ),
    ]
